# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadComments',
            new_name='LeadComment',
        ),
    ]
