# Generated by Django 4.2.5 on 2023-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_leadcomments_leadcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
    ]
