# Generated by Django 4.2.5 on 2023-09-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_source_delete_leadsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcomment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone1',
        ),
    ]
